/**
 * Setu 2.0 - Real Pan-India Channel Partners Directory
 * Official State Channelising Agencies (SCAs), Nodal Institutions & Lead Banks
 * Ministry of Social Justice & Empowerment (MoSJE) & NSFDC Channel Network
 */

const REAL_PARTNERS = [
  // ==========================================
  // NATIONAL NODAL INSTITUTIONS (Up to ₹10-15 Cr)
  // ==========================================
  {
    id: "ifci-hq",
    name: "IFCI Venture Capital Funds Ltd. (Headquarters)",
    type: "National Nodal Agency (MoSJE)",
    state: "Delhi",
    city: "New Delhi",
    address: "IFCI Tower, 61 Nehru Place, New Delhi - 110019",
    pincode: "110019",
    phone: "011-41732000 / 011-26453011",
    email: "vcfsc@ifciventure.com",
    website: "https://vcfsc.in",
    handles: ["vcfsc", "cegssc", "asiim"],
    maxFundingLimit: 150000000, // ₹15 Crore
    isEligible: true,
    statusNote: "Direct nodal manager for VCF-SC equity capital and CEGSSC credit guarantees up to ₹10 Crore across India."
  },
  {
    id: "sidbi-hq",
    name: "SIDBI / Stand-Up Mitra Nodal Cell",
    type: "National Nodal Bank",
    state: "Maharashtra",
    city: "Mumbai",
    address: "Swavalamban Bhavan, C-11, G-Block, Bandra Kurla Complex, Bandra (E), Mumbai - 400051",
    pincode: "400051",
    phone: "1800-180-1111 / 022-67531100",
    email: "standupmitra@sidbi.in",
    website: "https://standupmitra.in",
    handles: ["standup"],
    maxFundingLimit: 10000000, // ₹1 Crore
    isEligible: true,
    statusNote: "National operational clearing agency for Stand-Up India across 1.4+ Lakh scheduled commercial bank branches."
  },

  // ==========================================
  // STATE CHANNELISING AGENCIES (SCAs - MoSJE / NSFDC)
  // ==========================================
  {
    id: "sca-mh",
    name: "Mahatma Phule Backward Class Development Corporation (MPBCDC) / MAHAPREIT",
    type: "State Channelising Agency (SCA)",
    state: "Maharashtra",
    city: "Mumbai",
    address: "501, 5th Floor, Keshava Building, Bandra Kurla Complex, Bandra East, Mumbai - 400051",
    pincode: "400051",
    phone: "022-26470081 / 022-26470082",
    email: "support@mahapreit.in",
    website: "https://mahapreit.in",
    handles: ["micro", "msy", "term", "edu", "green"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Active accreditation with regular NSFDC credit allocation for Maharashtra."
  },
  {
    id: "sca-dl",
    name: "Delhi SC/ST/OBC/Minorities Financial & Development Corp. (DSCFDC)",
    type: "State Channelising Agency (SCA)",
    state: "Delhi",
    city: "Delhi",
    address: "Ambedkar Bhawan, Sector 16, Rohini, Delhi - 110089",
    pincode: "110089",
    phone: "011-27882208 / 011-27882209",
    email: "md.dscfdc@delhi.gov.in",
    website: "https://dscfdc.delhi.gov.in",
    handles: ["micro", "msy", "term", "edu", "green"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Processes applications across all 11 Delhi revenue districts."
  },
  {
    id: "sca-wb",
    name: "West Bengal SC, ST Development & Finance Corporation (WBSCSTDFC)",
    type: "State Channelising Agency (SCA)",
    state: "West Bengal",
    city: "Kolkata",
    address: "CF-217/A/1, Sector-I, Salt Lake City, Kolkata - 700064",
    pincode: "700064",
    phone: "033-23214811 / 033-23214812",
    email: "wbscstdfc@gmail.com",
    website: "https://wbscstdfc.gov.in",
    handles: ["micro", "msy", "term", "edu", "green"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Fully digitized verification connected to West Bengal Caste Certificate portal."
  },
  {
    id: "sca-tn",
    name: "Tamil Nadu Adi Dravidar Housing & Development Corp. (TAHDCO)",
    type: "State Channelising Agency (SCA)",
    state: "Tamil Nadu",
    city: "Chennai",
    address: "No. 31, Cenotaph Road, Teynampet, Chennai - 600018",
    pincode: "600018",
    phone: "044-24310231 / 044-24310232",
    email: "ho@tahdco.com",
    website: "https://tahdco.tn.gov.in",
    handles: ["micro", "msy", "term", "edu", "green"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Special state interest subvention provides up to 30% capital subsidy in conjunction with NSFDC."
  },
  {
    id: "sca-ka",
    name: "Dr. B. R. Ambedkar Development Corporation Ltd. (ADCL)",
    type: "State Channelising Agency (SCA)",
    state: "Karnataka",
    city: "Bengaluru",
    address: "9th & 10th Floor, Vishweshwaraiah Mini Tower, Dr. Ambedkar Veedhi, Bengaluru - 560001",
    pincode: "560001",
    phone: "080-22864388 / 080-22864389",
    email: "md@adcl.karnataka.gov.in",
    website: "https://adcl.karnataka.gov.in",
    handles: ["micro", "msy", "term", "edu", "green"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Direct portal integration with Karnataka Seva Sindhu."
  },
  {
    id: "sca-up",
    name: "Uttar Pradesh Scheduled Castes Finance & Development Corp. (UPSCFDC)",
    type: "State Channelising Agency (SCA)",
    state: "Uttar Pradesh",
    city: "Lucknow",
    address: "Prag Narain Road, Butler Colony, Lucknow - 226001",
    pincode: "226001",
    phone: "0522-2287236 / 0522-2287237",
    email: "upscfdc@rediffmail.com",
    website: "https://upscfdc.up.gov.in",
    handles: ["micro", "msy", "term", "edu"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Present across all 75 districts through District Social Welfare Officers (DSWO)."
  },
  {
    id: "sca-gj",
    name: "Gujarat Scheduled Castes Development Corporation (GSCDC)",
    type: "State Channelising Agency (SCA)",
    state: "Gujarat",
    city: "Gandhinagar",
    address: "Block No. 4, 1st Floor, Dr. Jivraj Mehta Bhavan, Gandhinagar - 382010",
    pincode: "382010",
    phone: "079-23253245 / 079-23253246",
    email: "gscdc-gnr@gujarat.gov.in",
    website: "https://gscdc.gujarat.gov.in",
    handles: ["micro", "msy", "term", "edu"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Integrated with Digital Gujarat portal for online document verification."
  },
  {
    id: "sca-rj",
    name: "Rajasthan SC & ST Finance and Dev. Co-operative Corp. (Anuja Nigam)",
    type: "State Channelising Agency (SCA)",
    state: "Rajasthan",
    city: "Jaipur",
    address: "Nehru Sahkar Bhawan, 4th Floor, Lal Kothi, Tonk Road, Jaipur - 302005",
    pincode: "302005",
    phone: "0141-2740283 / 0141-2740284",
    email: "ed.anujanigam@rajasthan.gov.in",
    website: "https://anujanigam.rajasthan.gov.in",
    handles: ["micro", "msy", "term", "edu", "green"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Applications processed via SSO Rajasthan & Jan Aadhaar linkage."
  },
  {
    id: "sca-pb",
    name: "Punjab Scheduled Castes Land Development & Finance Corp. (PSCFC)",
    type: "State Channelising Agency (SCA)",
    state: "Punjab",
    city: "Chandigarh",
    address: "SCO 101-103, Sector 17-C, Chandigarh - 160017",
    pincode: "160017",
    phone: "0172-2702758 / 0172-2702759",
    email: "pscfc@punjab.gov.in",
    website: "https://pscfc.punjab.gov.in",
    handles: ["micro", "term", "edu"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "High operational allocation for agro-allied and small trading units."
  },
  {
    id: "sca-od",
    name: "Odisha SC and ST Dev. Finance Co-operative Corp. (OSFDC)",
    type: "State Channelising Agency (SCA)",
    state: "Odisha",
    city: "Bhubaneswar",
    address: "Lewis Road, Samantarapur, Bhubaneswar - 751002",
    pincode: "751002",
    phone: "0674-2430038 / 0674-2430039",
    email: "osfdc@nic.in",
    website: "https://osfdc.nic.in",
    handles: ["micro", "msy", "term", "edu"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Special focus on coastal artisans, rural SHGs and micro-credit."
  },
  {
    id: "sca-ap",
    name: "AP Scheduled Castes Co-operative Finance Corp. Ltd. (APSCCFC)",
    type: "State Channelising Agency (SCA)",
    state: "Andhra Pradesh",
    city: "Vijayawada",
    address: "D.No. 40-1-63, MG Road, Vijayawada - 520010",
    pincode: "520010",
    phone: "0866-2495577 / 0866-2495578",
    email: "md_apsccfc@yahoo.com",
    website: "https://apsccfc.ap.gov.in",
    handles: ["micro", "msy", "term", "edu"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Synchronized with Navasakam village/ward secretariat delivery mechanism."
  },
  {
    id: "sca-ts",
    name: "Telangana Scheduled Castes Co-operative Dev. Corp. (TSCCDC)",
    type: "State Channelising Agency (SCA)",
    state: "Telangana",
    city: "Hyderabad",
    address: "Damodaram Sanjeevaiah Sankshema Bhavan, Masab Tank, Hyderabad - 500028",
    pincode: "500028",
    phone: "040-23395722 / 040-23395723",
    email: "vcmd_tsccdc@telangana.gov.in",
    website: "https://tsccdc.telangana.gov.in",
    handles: ["micro", "msy", "term", "edu"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Works in tandem with state Dalit Bandhu initiative."
  },
  {
    id: "sca-kl",
    name: "Kerala State Development Corp. for SC and ST Ltd. (KSDC)",
    type: "State Channelising Agency (SCA)",
    state: "Kerala",
    city: "Thrissur",
    address: "Town Hall Road, Thrissur - 680020",
    pincode: "680020",
    phone: "0487-2331074 / 0487-2331075",
    email: "ksdcscst@gmail.com",
    website: "https://ksdc-scst.kerala.gov.in",
    handles: ["micro", "msy", "term", "edu", "green"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Lowest default rate amongst SCAs; high uptake for foreign education loans."
  },
  {
    id: "sca-br",
    name: "Bihar State SC Co-operative Development Corp. (BSSCDC)",
    type: "State Channelising Agency (SCA)",
    state: "Bihar",
    city: "Patna",
    address: "Social Welfare Complex, Bailey Road, Patna - 800001",
    pincode: "800001",
    phone: "0612-2223842",
    email: "md_scstcorp_bihar@yahoo.co.in",
    website: "https://scst.bihar.gov.in",
    handles: ["micro", "term", "edu"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Partnered with Bihar Mahila Vikas Nigam for women entrepreneur schemes."
  },
  {
    id: "sca-mp",
    name: "Madhya Pradesh State SC Development Corporation",
    type: "State Channelising Agency (SCA)",
    state: "Madhya Pradesh",
    city: "Bhopal",
    address: "Rajiv Gandhi Bhawan, 35 Shyamla Hills, Bhopal - 462002",
    pincode: "462002",
    phone: "0755-2551465 / 0755-2551466",
    email: "mpsc_corp@mp.gov.in",
    website: "https://scdevelopmentmp.nic.in",
    handles: ["micro", "msy", "term", "edu"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "District Antyavasayi Co-operative Societies coordinate regional disbursement."
  },
  {
    id: "sca-as",
    name: "Assam State Development Corp. for Scheduled Castes Ltd.",
    type: "State Channelising Agency (SCA)",
    state: "Assam",
    city: "Guwahati",
    address: "Ganeshguri, Chariali, Dispur, Guwahati - 781006",
    pincode: "781006",
    phone: "0361-2234055",
    email: "sc_assam@gov.in",
    website: "https://wptbc.assam.gov.in",
    handles: ["micro", "term", "edu"],
    maxFundingLimit: 5000000,
    isEligible: true,
    statusNote: "Handles channel finance across Brahmaputra and Barak valleys."
  },

  // ==========================================
  // PUBLIC SECTOR & COMMERCIAL BANKS (Priority Sector / Stand-Up Cells)
  // ==========================================
  {
    id: "bank-sbi",
    name: "State Bank of India — SME & Priority Sector Cell",
    type: "Public Sector Bank (PSB)",
    state: "All India",
    city: "National Network (22,000+ Branches)",
    address: "State Bank Bhavan, Madame Cama Road, Nariman Point, Mumbai - 400021",
    pincode: "400021",
    phone: "1800-11-2211 / 1800-425-3800",
    email: "agm.sme@sbi.co.in",
    website: "https://sbi.co.in/web/business/sme",
    handles: ["standup", "cegssc", "pmegp", "mudra", "term"],
    maxFundingLimit: 100000000, // ₹10 Crore
    isEligible: true,
    statusNote: "Mandated Stand-Up India lead bank in 400+ districts; Member Lending Institution for CEGSSC."
  },
  {
    id: "bank-pnb",
    name: "Punjab National Bank — SC/ST & Micro-Enterprise Cell",
    type: "Public Sector Bank (PSB)",
    state: "All India",
    city: "National Network (10,000+ Branches)",
    address: "Plot No. 4, Sector 10, Dwarka, New Delhi - 110075",
    pincode: "110075",
    phone: "1800-180-2222",
    email: "sme@pnb.co.in",
    website: "https://pnbindia.in",
    handles: ["standup", "cegssc", "pmegp", "mudra", "term"],
    maxFundingLimit: 100000000,
    isEligible: true,
    statusNote: "Key partner for CEGSSC and Stand-Up India in North & Central India."
  },
  {
    id: "bank-canara",
    name: "Canara Bank — Priority Sector & Financial Inclusion Division",
    type: "Public Sector Bank (PSB)",
    state: "All India",
    city: "National Network (9,700+ Branches)",
    address: "112, J.C. Road, Bengaluru - 560002",
    pincode: "560002",
    phone: "1800-425-0018",
    email: "fid@canarabank.com",
    website: "https://canarabank.com",
    handles: ["standup", "cegssc", "pmegp", "mudra", "edu"],
    maxFundingLimit: 100000000,
    isEligible: true,
    statusNote: "Lead bank for Stand-Up India and higher education loans in Southern states."
  },
  {
    id: "bank-bob",
    name: "Bank of Baroda — MSME & Priority Credit Hub",
    type: "Public Sector Bank (PSB)",
    state: "All India",
    city: "National Network (8,200+ Branches)",
    address: "Baroda Bhavan, R.C. Dutt Road, Alkapuri, Vadodara - 390007",
    pincode: "390007",
    phone: "1800-5700",
    email: "msme.bcc@bankofbaroda.com",
    website: "https://bankofbaroda.in",
    handles: ["standup", "cegssc", "pmegp", "mudra"],
    maxFundingLimit: 100000000,
    isEligible: true,
    statusNote: "Recognized as leading lender under Stand-Up India and CEGSSC guarantees in West India."
  }
];

if (typeof window !== "undefined") {
  window.REAL_PARTNERS = REAL_PARTNERS;
}
